ministryofjustice/make-recall-decision-api

docker-compose.yml, scripts/start-local-services.sh
Now we're calling out to hmpps-auth, I've added it as a dependency for
the application (in the docker-compose file) and added the needed config
to allow the local docker build to start up (this will be needed for E2E
tests).
=> Add hmpps-auth as a dependency of the app

Dockerfile, build.gradle.kts, docker-compose.yml, helm_deploy/make-recall-decision-api/values.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/ResourceServerConfiguration.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/health/HealthCheckTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/health/InfoTest.kt
This moves all the springboot management functions onto port 8081,
enables prometheus metrics and also configures the k8s environment to
get them scraped.
=> MRD-11: Enable prometheus metrics

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/HealthController.kt
Now that all the management functions have been moved to port 8081 and
made private to the k8s cluster we need something that doesn't need
authentication for external services to ping.
This will be used by `make-recall-decision-ui` (in it's healthchecks)
and pingdom when I set that up.
=> (Re-)Add an external `/health` endpoint.

helm_deploy/make-recall-decision-api/values.yaml
This will ensure we get regular heartbeat data on our upstream dependencies
=> Hit the /health endpoint as the readiness check

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/SentryConfig.kt
This cuts down on a bit of log noise.
ref: https://mojdt.slack.com/archives/C03B57W0ALT/p1652696693028719?thread_ts=1652691808.694999&cid=C03B57W0ALT
=> Don't log the OperationID on the /health endpoint

build.gradle.kts
This resolves the netty (false positive) CVE warnings - ref https://mojdt.slack.com/archives/C69NWE339/p1652770667158019
=> Update the hmpps gradle-spring-boot plugin

build.gradle.kts
Fix for security scan on issues CVE-2022-22978 and CVE-2022-22976.
=> NO_JIRA_spring-version-bump:

.circleci/config.yml, README.md, build.gradle.kts, docker-compose-integration-test-postgres.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/MakeRecallDecisionApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/RecommendationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/RecommendationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/exception/NoRecommendationFoundException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/jpa/entity/EntityWithId.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/jpa/entity/RecommendationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/main/resources/application.yml, src/main/resources/db/migration/V1_2__RECOMMENDATIONS_TABLE.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/RecommendationControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/health/HealthCheckTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationServiceTest.kt
H2 doesn't support json blobs, which is the reason for the switch here.
In this PR I've also changed the Circle CI build environment from the standard Docker Container to an Ubuntu VM.
Our tests need a VM in order to use the Docker Postgres container in CI.
=> Switched H2 embedded test database for a Postgres Docker container

src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt
The change restores the speed of the test run to 4m33s (on my machine).
=> Speed up Integration Tests

src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/RecommendationToPartADataMapperTest.kt
The enriched test will fail if any of the existing Part A keys are changed.
=> Added test data to cover all alternatives

renovate.json
Quite a lot of other services are reusing the ARN renovate config. This seems to group all minor updates into one PR so should make the Renovate PRs a lot less noisy.
=> Reuse ARN renovate config

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/RecommendationToPartADataMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/RecommendationToPartADataMapperTest.kt
eg generate a Part A without answering the 'arrest issues' or 'contraband' questions. The answers should be blank but are 'No'. This PR adjusts the `convertBooleanToYesNo` logic so if the property isn't set, an empty string is returned.
=> MRD-559 - Part A mapper - If a boolean is not set, return empty string

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskServiceTest.kt
Updated matching rules of assessment info to allow offence details to be shown on overview screen where the offence codes do not match across OaSys and Delius.
=> mrd-700_show-offence-description-when-no-match

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/LicenceConditionsResponse.kt
This fixes a bug in the backward-compatibility in the previous PR, that was picked up in our end-to-end tests. Note: the backward-compatibility code will be removed in another PR as soon as the UI has been updated to use the new fields, so this won't be around long.
=> PI-577 Set licence conditions to active

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/DeliusClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/MakeRecallDecisionApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/MrdEvent.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/exception/NoStaffCodeException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationServiceTest.kt
The probation integration consumer now accepts the "username" instead, which means you no longer need to call an extra endpoint to get the user's staff code.
=> PI-577 Remove staff code from management-oversight message

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/RecommendationControllerTest.kt
allow new recommendation to be created when active recommendation already present with trigger flag set
=> no_jira-fix-for-create-recommendation-with-trigger

applicationinsights.dev.json, applicationinsights.json
The app insights Java agent from 3.4.0 defaults to rate limited sampling. 
This change matches the change in the HMPPS Kotlin template
=> Set application insights sampling to 100%

helm_deploy/make-recall-decision-api/Chart.yaml
This means the latest patch version will be used, reducing the burden on keeping this up to date.
=> Remove patch version from helm chart versions

renovate.json
Explicit logback versions 1.2.13 are requested in order to resolve a vulnerability. These cannot be upgraded beyond 1.2 until other dependencies that rely on them are upgraded.
=> Configure Renovate to ignore logback attempt 2

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientConfiguration.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt
It's debatable whether 500 should be retried, but this change has been prompted by seeing 500 responses that we definitely wouldn't want to retry.
=> MRD-2359 Finesse the conditions for retry

src/main/resources/application.yml
This should mean that we get the chance to retry when hit by the "ingress issue" but won't miss any successful calls.
=> Reduce CVL timeout to 20s

src/main/resources/application.yml
Performance tests suggest that 60s is only the 78th percentile
=> Increase timeout for PPUD Automation

renovate.json
The Renovate config is now in line with  hmpps-kotlin-template
=> Update renovate config to ignore major versions

suppressions.xml
maven/com.deepoove/poi-tl
is our DocX generating package which references dependency
org.apache.commons/commons-collections4/4.4/
We are using the latest (non-beta) version of poi-tl (1.12.2) and the latest version of org.apache.commons/commons-collections4/ (4.4)
=> Supressing CVE-2015-6420 since it's specific to some Cisco software

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt
Switch to Jackson and ensuring input param refs aren't changed for possible failure retries.
Reordering domain events to ensure they're only fired after a successful update, and not per retry.
=> Mrd 2554 failure retries could result in lost data

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PrisonerApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PrisonerApiServiceTest.kt
NOMIS can store invalid facial image IDs which will cause 404s during the offender retrieval.
This update protects against any failure in the non-essential image lookup
=> coping with facial image id lookup failures

.trivyignore
Suppression for tomcat vulnerability affecting jsp compilation in the default servlet can be suppressed as we do not use the default servlet and haven't configured it for write either
=> Suppression of CVE-2024-50379 trivy scan alert

build.gradle.kts
both fixed in logback ver 1.5.13, but that is not included in the latest spring boot 3.4.1 release, which still targets 1.5.12, therefore forcing 1.5.14
see https://mojdt.slack.com/archives/C69NWE339/p1734943189790819
=> OWASP scan vuln CVE-2024-12798 and CVE-2024-12801

.trivyignore
CVE report indicates Java 21 projects are unaffected, so we can suppress:
https://avd.aquasec.com/nvd/2024/cve-2024-56337/
=> Suppress CVE-2024-56337

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/MrdTextConstants.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/testutil/TestDataHelper.kt
The DEFAULT_DATE_TIME_FOR_NULL_VALUE is used whenever comparisons of entities by a date time is needed. Any entity with a null date time will be considered to have said constant as its date and time instead. The constant was set to epoch (1970-01-01T00:00:00) with the intention of null-date entities being considered older than those with non-null dates. This is being changed to an earlier date (in 1200), as there's still a (remote) possibility that an offender has an entity associated to them in the DB (e.g. an OSP assessment) earlier than epoch, which could result in incorrect ordering. This was noticed when a test using random values (RiskScoreConverterTest) produced early enough dates to result in unexpected ordering.
Note that using LocalDateTime.MIN.toString() was considered, but at …
=> Change default date time for nulls

build.gradle.kts
Bump non major gradle dependencies excluding: 
- uk.gov.justice.hmpps.gradle-spring-boot
- jvm
- plugin.jvm
- plugin.spring
whose increments cause deprecation warnings regarding OAuth2 aspects which require refactoring:
```
w: file:.../make-recall-decisionpi/src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientUserEnhancementConfiguration.kt:17:8 'class DefaultClientCredentialsTokenResponseClient : Any, OAuth2AccessTokenResponseClient<OAuth2ClientCredentialsGrantRequest!>' is deprecated. Deprecated in Java.
w: file:.../make-recall-decision-api/src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientUserEnhancementConfiguration.kt:92:55 'constructor(): DefaultClientCredentialsTokenResponseClient' is deprecated. Deprecated in Java. …
```
=> bump non maj gradle deps

src/main/resources/application.yml
Reverting management endpoints (health/info/prometheus) back to standard HTTP ports.
These were overridden to use 8081 on 03/05/22 by Darren Oakley for MRD-11
=> MRD-2526 Fixing info endpoint (move to standard port)

Dockerfile, docker-compose-e2e.yml, docker-compose.yml, helm_deploy/make-recall-decision-api/values.yaml, scripts/start-local-services.sh, src/main/resources/application.yml
Reverting management endpoints (health/info/prometheus) back to standard HTTP ports.
These were overridden to use 8081 on 03/05/22 by Darren Oakley for MRD-11
=> Mrd 2526 fixing info endpoint

fake-prison-api/__files/get-agency-MDI.json, fake-prison-api/mappings/get-agency-MDI.json, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/Agency.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PrisonerApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/PrisonApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PrisonerApiServiceTest.kt
Changing the endpoint used to retrieve prison/agency details by prisonId because the new endpoint facilitates querying inactive prisons (a possible scenario).
=> MRD-2570 Ensuring we cope with inactive prisons (aka Progress Booking On when no Index Offence in NOMIS)

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/CreateRecallRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/PpudCreateRecallRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PpudService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/PpudAutomationApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/PpudControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PpudServiceTest.kt
Removing all referenced to the ROSHLevel no longer passed when creating a recall since the ppud minutes that it previously created are now created from an individual call from the UI, not PPUD API
=> MRD-2610 Combining duplicate mintes

.circleci/config.yml, docker-compose-e2e.yml, docker-compose-integration-test-postgres.yml, docker-compose-postgres.yml, docker-compose.yml, src/main/resources/application.yml
Revert to stnd redis port
Explicitly configure the API to depend on the redis service setup in the UI project, and explicitly set the host via env. var.
=> Mrd 2634 - CircleCI redis config shared between projects

.circleci/config.yml, docker-compose-e2e.yml, docker-compose-integration-test-postgres.yml, docker-compose-postgres.yml, docker-compose.yml, src/main/resources/application.yml
Reverting to standard redis port
Removing the depends_on attribute, retaining the REDIS_HOST env var
=> Mrd 2634 CircleCI config for shared redis instance

fake-ppud-automation-api/__files/reference-released-unders.json
Update reference-released-unders to more realistic values that also don't trigger the escape character in options bug in the version of cypress we are currently bound to.
This is because the current version of cypress we are using does not properly escape values with quotation marks but attempting to upgrade our cypress package led to a long road of dependency updates that ended in a an eventual error within one one of these said dependencies.
Seeing as this is only test data and we do not expect this to appear in dev etc and this e2e to work has grown so large due to all of the facets involved, this will solve the immediate issue of this fake data causing issue and reviewing package version will be deferred to it's piece of work to work through the e2e and test and see about cleaning up …
=> [MRD-2557] Valid test data values

fake-delius-integration-api/__files/search-not-found.json, fake-delius-integration-api/mappings/search-not-found.json, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/DeliusClient.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/DeliusClientTest.kt
[MRD-2748]()http://dsdmoj.atlassian.net/browse/MRD-2748)
Delius /case-summary/{crn} now returns a 404 rather than an empty response when not found, handle this and return the already existing null when this occurs.
[MRD-2748]: https://dsdmoj.atlassian.net/browse/MRD-2748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [MRD-2748] Handle search by CRN 404 response

fake-delius-integration-api/__files/search-cvl-no-additional.json, fake-delius-integration-api/__files/search-cvl-no-bespoke.json, fake-prison-api/__files/sentences-offences-X098092-12.json, fake-prison-api/__files/sentences-offences-X098092-13.json, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/PrisonApiController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/Sentence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/SentenceSequence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/recommendation/NomisIndexOffence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/prisonapi/PrisonerApiService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/prisonapi/PrisonerApiServiceTest.kt
[MRD-2721](https://dsdmoj.atlassian.net/browse/MRD-2721)
Update PrisonApiService to collect consecutiveToSequence for Sentences and calculate the sentences this group each with
[MRD-2721]: https://dsdmoj.atlassian.net/browse/MRD-2721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Note the comment below as our understanding of consecutive/concurrent sentences has evolved since we began this work.
Additionally, this now incorporates changes to support [MRD-2721](https://dsdmoj.atlassian.net/browse/MRD-2729) as these changes are now inextricably linked.
=> MRD-2721: Consecutive Sentences data

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Set Preprod and Prod document template setting to default to the 'current' template so we can deploy 'as is' until we further develop versioning for recommendations.
=> Template config settings for Preprod/ProdFTR48
