.circleci/config.yml, README.md, helm_deploy/make-recall-decision-api/Chart.yaml, helm_deploy/make-recall-decision-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
- Setup preprod and prod deployments
- Setup alert routing
- Update the helm charts in use to the latest versions
=> Infra Updates

README.md, scripts/reload-local-service-api.sh, scripts/reload-local-service-ui.sh
I also added in some simple "reload" scripts for the API and UI apps.
=> Document running the apps locally

helm_deploy/make-recall-decision-api/values.yaml
These are needed for talking to nDelius etc.
=> Add the `SYSTEM_CLIENT` environment variables

.circleci/config.yml, build.gradle.kts, helm_deploy/make-recall-decision-api/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/CustomTracesSamplerCallback.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/MakeRecallDecisionApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/SentryConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebConfig.kt
Setup error reporting and deployment tracking in Sentry.
=> MRD-10: Sentry Setup

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/AuthAwareTokenConverter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/ResourceServerConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/OverviewController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/Domain.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/OverviewControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/helper/JwtAuthHelper.kt
https://dsdmoj.atlassian.net/browse/MRD-29
=> MRD-29 Provide dummy response for overview endpoint

.circleci/config.yml, scripts/run-e2e-tests.sh
This invokes and follows the E2E tests in the UI project and blocks
promotion through the tiers if they fail.
=> Run the E2E tests after deployment

docker-compose.yml, scripts/start-local-services.sh, scripts/stop-local-services.sh
- Remove the `network_mode: "host"` directive from app (having this is bad)
- Put the `app` on port 8080 - this is where UI expects to find it
- Update the auth healthcheck
- Make the start/stop scripts faster and more robust
=> A few minor tweaks to the docker-compose setup

docker-compose.yml, scripts/reload-local-service-api.sh, scripts/reload-local-service-ui.sh, scripts/start-local-services.sh, scripts/stop-local-services.sh, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/OverviewController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/RiskController.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml
This change along with https://github.com/ministryofjustice/hmpps-auth/pull/1244 will allow us to use auth locally in the same manner to dev.
=> Fix local auth integration.

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/resources/application.yml
added environment variable to helm_deploy files for offender-search-api url.
=> MRD-18_search-by-crn-helm-yaml-addition

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/OffenderSearchController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/AllOffenderDetailsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/Conviction.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/Offence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/Sentence.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchService.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/CommunityApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/AllOffenderDetailsResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/ConvictionsResponse.kt, src/test/resources/application-test.yml
This provides some of the case summary fields as a poc.
=> MRD-2_community-api-poc: Added CommunityApiClient.

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Corrected helm-deploy environment variable for preprod.
=> MRD-18_preprod-500-fix

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/resources/application-dev.yml
:Corrected community-api url variables.
=> MRD-43_MRD-120_person-details-and-overview_500-fix

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/health/CommunityApiHealth.kt, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/resources/application-test.yml
corrected anomalies i community-api config.
=> MRD-43_MRD-120_person-details-and-overview_500

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/MakeRecallDecisionApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/PersonDetailsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/SearchByCrnResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/AllOffenderDetailsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/ConvictionResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/RegistrationsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/offendersearchapi/OffenderDetailsResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/exception/PersonNotFoundException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonDetailsService.kt
Made community-api response fields nullable and added check w custom exception to handle scenario where no person is available.
>
=> MRD-43_MRD_120_handle-person-not-found-scenario

.circleci/config.yml, README.md, build.gradle.kts, build.sh, docker-compose.yml, helm_deploy/make-recall-decision-api/values.yaml, scripts/port-forward-db.sh, src/main/resources/application.yml, src/main/resources/db/migration/README.md, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/resources/application-test.yml
- Get connection details from secrets in kubernetes
- Setup PostgreSQL in docker-compose for local development etc
- Connect the app to PostgreSQL
- Setup database migrations using `flyway`
- Add a proxy script to allow devs to connect to db's in `dev` and `preprod`
=> MRD-126: Setup PostgreSQL

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/health/HealthCheckTest.kt
:Added minimalist embedded h2 db to allow SpringBootTests to pass.
=> NO_JIRA_h2-embedded-db

build.gradle.kts, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/LicenceHistoryController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/ContactSummaryResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/LicenceHistoryResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/ContactSummaryResponseCommunity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/communityapi/ReleaseSummaryResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceHistoryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/CommunityApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/LicenceHistoryControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/ContactSummaryResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/ReleaseResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceHistoryServiceTest.kt, src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Provide a new endpoint for licence history
=> MRD-124 Licence History Endpoint

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/CommunityApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/OffenderSearchApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/MakeRecallDecisionApiExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/SentryConfig.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/exception/ClientTimeoutException.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceHistoryService.kt, src/main/resources/application.yml, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/CaseOverviewControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/LicenceHistoryControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/OffenderSearchControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/PersonDetailsControllerTest.kt, src/test/resources/application-test.yml
Added increased timeout for talking to nDe…lius APIs with exception handling.
=> MRD-138_connection-timeout

Dockerfile
Reverts ministryofjustice/make-recall-decision-api#104
=> Revert "Update dependency openjdk to v19"

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/ArnApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/RiskResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/ArnApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/RiskControllerTest.kt
A 404 on ARN RoSH is now handled with a log message to allow the user to proceed to the Risk screen.
=> MRD-121_permit-risk-screen-to-proceed-when-no-summary-available:

fake-arn-api/__files/X098092-current-scores.json, fake-arn-api/__files/X098092-historical-scores.json, fake-arn-api/mappings/X098092-current-scores.json, fake-arn-api/mappings/X098092-historical-scores.json, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/ArnApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/RiskResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/oasysarnapi/CurrentScoreResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/oasysarnapi/HistoricalScoreResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/ArnApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/RiskControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/arn/CurrentRiskScoresResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/arn/HistoricalScoresResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/arn/RoSHSummaryResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/ndelius/MappaDetailsResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskServiceTest.kt
prediction and historical scores.
=> MRD-195_risk-endpoint-prediction-and-historical-scores:

build.gradle.kts
Reverts ministryofjustice/make-recall-decision-api#124
=> Revert "Update dependency org.flywaydb:flyway-core to v8.5.13"

README.md, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/WebClientUserEnhancementConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonDetailsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessValidator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonalDetailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ServiceTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessExcludedResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessRestrictedResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessValidatorTest.kt
fixed OffenderSearchService to allow handling of restricted/excluded crns for user.
=> MRD-299_bug-fix-for-offender-search-endpoint:

build.gradle.kts, docker-compose-functional-test.yml, scripts/clean-up-docker.sh, scripts/wait-for-it.sh, src/functional-test/kotlin/ft/FunctionalTest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/ContactHistoryController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/LicenceConditionsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/OffenderSearchController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/OverviewController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/PersonDetailsController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/RecommendationController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/controller/RiskController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/RecommendationRequest.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonDetailsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessValidator.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonalDetailServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ServiceTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessValidatorTest.kt
POC for blackbox/out of process functional test.
To run` ./gradlew functional-test`
=> MRD-289_functional-test_poc:

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/ConvictionResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/ndelius/Conviction.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/ndelius/Custody.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/ndelius/EstablishmentType.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/ndelius/Institution.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/ndelius/KeyDates.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/client/CommunityApiClientTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/CaseOverviewControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/LicenceConditionsControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/ndelius/convictions/ConvictionsResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/responses/ndelius/convictions/NonCustodialConvictionsResponse.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ServiceTestBase.kt
Reverts ministryofjustice/make-recall-decision-api#257
=> MRD-398 Added is custodial flag to overview and licence condition responses

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/RecommendationToPartADataMapper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PartATemplateReplacementServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/RecommendationToPartADataMapperTest.kt
AC8 in https://dsdmoj.atlassian.net/browse/MRD-603
=> MRD-603 - If indeterminate sentence, write N/A to part A Q22

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/recommendation/RecommendationResponse.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/jpa/entity/RecommendationEntity.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/DateTimeHelper.kt, src/main/resources/db/migration/V1_9__RECOMMENDATIONS_TABLE.sql, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/MrdTestDataBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PartATemplateReplacementServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/RecommendationToPartADataMapperTest.kt
- Changed the formatting of the date to dd/mm/yyyy
- Time now in the local date time rather than UTC
=> MRD-591 Minor changes to the format of the Part A downloaded date time

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonDetailsService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonalDetailServiceTest.kt
=> MRD-706: Added business logic to set `noFixedAbode` on … address to true when a no fixed abode postcode is present

src/main/resources/application.yml
=> Fix for DataBufferLimitException on contact-history tab.

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/DocumentService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/DocumentControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/DocumentServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ServiceTestBase.kt
This reverts commit 6fe705ff667114321aca3a8751c61bab8a096df8.
=> Revert "mrd-1072_fix-download-document-hack:

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/client/DeliusClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt
Relates to: https://github.com/ministryofjustice/hmpps-probation-integration-services/pull/1388
=> PI-998 Handle null offence date

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/RecommendationStatusControllerTest.kt
fix for folllowing issues -
* old statuses set inactive when recommendation closed on trigger journey
* null active recommendation due to DOCUMENT_DOWNLOADED being set on trigger journey
=> no_jira_fix-for-null-active-recommedation-and-status-issues: 

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CreateAndVaryALicenceService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/DocumentService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsCoordinator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/LicenceConditionsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ManagementOversightService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/MrdEventsEmitter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/OffenderSearchService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/PersonDetailsService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationStatusService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/StaticRecommendationDataWrapper.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/UserAccessValidator.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/VulnerabilitiesService.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/DateTimeHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/MrdTestDataBuilder.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/documentmapper/PartADocumentMapperTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/helper/JwtAuthHelper.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/RiskControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/integration/controller/VulnerabilitiesControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/CaseSummaryOverviewServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ContactHistoryServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RecommendationServiceTabTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/RiskServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/ServiceTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/service/VulnerabilitiesServiceTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/util/LogHelperTest.kt
This is to satisfy linting errors that occur in later versions
=> MRD-1712 Adding trailing commas

src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/domain/makerecalldecisions/PrisonOffenderSearchResponse.kt
[logs](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-08T00:00:00.000Z',to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.labels.app,negate:!f,params:(query:make-recall-decision-api),type:phrase),query:(match_phrase:(kubernetes.labels.app:make-recall-decision-api))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'167701b0-f8c0-11ec-b95c-1d65c3682287',key:kubernetes.namespace_name,negate:!f,params:(query:make-recall-decision-dev),type:phrase),query:(match_phrase:(kubernetes.namespace_name:make-recall-decision-dev))),('$state':(store:appState),meta:(alias:!n,disabled:!f,ind …
=> no_jira_prison-offender-response-npe: added nullable type for middleName

.circleci/config.yml, gradle.properties
Sonar seems to be causing the pipelines to fail. This will get the pipelines back working while the issue is fixed properly.
=> Temporarily remove sonar command

src/main/resources/db/migration/V1_29__HISTORY_INDEXING.sql
Commenting out the problematic rec_hist crnc index
=> backing out rec_hist crnc index

Dockerfile, docker-compose-e2e.yml, docker-compose.yml, helm_deploy/make-recall-decision-api/values.yaml, scripts/start-local-services.sh, src/main/resources/application.yml
Updating the metrics port to use the 'http' helm variable
=> Mrd 2526 fixing info endpoint

.circleci/config.yml, docker-compose-e2e.yml, docker-compose-integration-test-postgres.yml, docker-compose-postgres.yml, docker-compose.yml, src/main/resources/application.yml
reverting to standard redis port since cache shared by all pods in same k8s env
=> MRD-2634 Reverting to standard redis port

.circleci/config.yml, docker-compose-e2e.yml, docker-compose-integration-test-postgres.yml, docker-compose-postgres.yml, docker-compose.yml, src/main/resources/application.yml
Rrevert to stnd redis port
Setting shares network (external)
=> Mrd 2634 circeCI/docker config for sharing redis

docker-compose.yml
Re-implementing a confused PR.
Removing depends_on attribute
=> MRD-2634 CircleCI and Docker config tweaks

docker-compose.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/makerecalldecisionapi/config/CacheConfiguration.kt
Additional logging output to show cache mode.
docker-compose:
Removing deprecated version key.
Additional Spring Redis Config env vars.
Removing unnecessary REDIS_HOST env var.
=> MRD-2634 Caching config
